# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [1]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [4]:
numpy.version.version 

'1.20.2'

In [37]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### Q3 : Créer un vecteur nul de taille 10

In [39]:
vecteur_t_10 = np.array([0. for x in range(10)]); vecteur_t_10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.zeros(10, dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 5ème place (index 4) du vecteur

In [21]:
vecteur_t_10[4] = 1
vecteur_t_10

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [41]:
vecteurZ_t_40 = np.arange(10, 50)
vecteurZ_t_40

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [44]:
np.flip(vecteurZ_t_40)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [42]:
vecteurZ_t_40[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [48]:
matrice_3_3 = np.arange(9).reshape(3, 3)
matrice_3_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [46]:
ident = np.identity(3)

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [52]:
np.random.random((3,3,3))

array([[[0.67303955, 0.08975944, 0.16144705],
        [0.68568637, 0.88879508, 0.86182188],
        [0.7070408 , 0.45564064, 0.38326133]],

       [[0.33514198, 0.2281971 , 0.1778509 ],
        [0.9795791 , 0.30640219, 0.10544036],
        [0.56114048, 0.50509803, 0.81042862]],

       [[0.6640808 , 0.93169897, 0.59352695],
        [0.29105252, 0.79304563, 0.79772945],
        [0.61019996, 0.12262943, 0.45204303]]])

In [ ]:
np.random.randint()

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [9]:
matrice_10_10 = np.random.random((10,10)); matrice_10_10

array([[0.60228117, 0.21596581, 0.79087283, 0.57220225, 0.25541085,
        0.85150288, 0.28265219, 0.54514795, 0.21019229, 0.43986866],
       [0.71556444, 0.31378473, 0.65419785, 0.70390836, 0.00902654,
        0.09784379, 0.33740151, 0.16618463, 0.30339442, 0.26810966],
       [0.81852985, 0.1350239 , 0.63372619, 0.76691851, 0.68226223,
        0.79647013, 0.35284101, 0.41664597, 0.84994313, 0.94999545],
       [0.83735502, 0.00147768, 0.08876447, 0.52255183, 0.10666373,
        0.5800483 , 0.46189283, 0.93482413, 0.33019741, 0.49453353],
       [0.15204273, 0.05619642, 0.68031075, 0.69896309, 0.09882129,
        0.91975981, 0.87536529, 0.00952394, 0.51307827, 0.64487006],
       [0.96418547, 0.36070733, 0.23808237, 0.05171252, 0.06425531,
        0.48655916, 0.77005036, 0.50629517, 0.20718953, 0.95124978],
       [0.89424784, 0.06922864, 0.83236914, 0.03570592, 0.53698593,
        0.17288877, 0.19023994, 0.3125327 , 0.35547466, 0.07887819],
       [0.25367351, 0.45476318, 0.9277783

In [10]:
print('min',matrice_10_10.min())
print('max', matrice_10_10.max())

min 0.0014776823107044423
max 0.9641854704485114


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [50]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [54]:
t = np.diagflat([1,2,3,4], -1)



#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [23]:
listT5Rdm = np.random.random(5); listT5Rdm


array([0.81989227, 0.59020591, 0.70435471, 0.75107161, 0.61313729])

In [24]:
listT5Rdm.sum()

3.47866179521025

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [25]:
np.average(listT5Rdm)

0.69573235904205

In [52]:
np.mean(listT5Rdm)

0.69573235904205

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :

In [29]:
l = [x for x in range(11)]
np.shape(l)

(11,)

In [66]:
t

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [58]:
np.size(t, axis = 0)

5

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [59]:
tabT10_01EX = np.linspace(0,1,11,endpoint=False)[1:]; tabT10_01EX

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [67]:
tabA = [1, 2, 3, 4 ,5]; 
tabB = np.flip(tabA); tabB

array([5, 4, 3, 2, 1])

In [64]:
np.array_equal(tabA, tabB)

False

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [69]:
Z = np.arange(10, dtype=np.float32); Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [70]:
Z = Z.astype(np.int32, copy=False)

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type

In [79]:
N = np.random.random((5,5)); N

array([[0.25354091, 0.8822792 , 0.80838724, 0.25511518, 0.19246651],
       [0.78122306, 0.29451731, 0.32463563, 0.91867242, 0.76184758],
       [0.40361344, 0.99690842, 0.26958449, 0.87429967, 0.68033314],
       [0.6354532 , 0.06204545, 0.83628303, 0.65186887, 0.41224552],
       [0.29972481, 0.62934802, 0.96653802, 0.36829113, 0.04262718]])

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)